#!/usr/bin/env python3
"""
generate_config.py — writes /data/config.py from environment variables.

Runs once, on first container boot only (entrypoint.sh skips this script if
/data/config.py already exists). This matters because proxy.py's in-app
"change admin password" feature rewrites config.py in place — if we
regenerated it from env vars on every boot, a password changed through the
UI would silently revert to the env var's value on the next container
restart.

Env vars:
  ADMIN_USERNAME               default "admin"
  ADMIN_PASSWORD                plaintext — hashed here with sha256
  ADMIN_PASSWORD_HASH            pre-hashed alternative; wins if both are set
  APP_SESSION_EXPIRY_SECONDS    default 28800 (8 hours)
  QUMULO_TOKEN_EXPIRY_DAYS      default 30

One of ADMIN_PASSWORD / ADMIN_PASSWORD_HASH is required — there's no silent
default, since this container is expected to end up reachable on a network.
"""
import hashlib, os, sys

CONFIG_PATH = "/data/config.py"

def fail(msg):
    print(f"generate_config.py: {msg}", file=sys.stderr)
    sys.exit(1)

def main():
    if os.path.exists(CONFIG_PATH):
        print(f"generate_config.py: {CONFIG_PATH} already exists, leaving it alone")
        return

    username     = os.environ.get("ADMIN_USERNAME", "admin")
    password     = os.environ.get("ADMIN_PASSWORD")
    password_hash = os.environ.get("ADMIN_PASSWORD_HASH")

    if not password_hash:
        if not password:
            fail("ADMIN_PASSWORD or ADMIN_PASSWORD_HASH must be set on first run "
                 "(no config.py found yet in the mounted /data volume).")
        password_hash = hashlib.sha256(password.encode()).hexdigest()

    try:
        session_expiry = int(os.environ.get("APP_SESSION_EXPIRY_SECONDS", 8 * 60 * 60))
    except ValueError:
        fail("APP_SESSION_EXPIRY_SECONDS must be an integer")
    try:
        token_expiry_days = int(os.environ.get("QUMULO_TOKEN_EXPIRY_DAYS", 30))
    except ValueError:
        fail("QUMULO_TOKEN_EXPIRY_DAYS must be an integer")

    contents = f'''"""
config.py — generated by docker/generate_config.py on first container boot.

This file lives in the /data volume, not the image, so it survives
container recreation — including admin password changes made through the
web UI, which rewrite ADMIN_PASSWORD_HASH below in place.
"""

ADMIN_USERNAME        = {username!r}
ADMIN_PASSWORD_HASH   = {password_hash!r}

APP_SESSION_EXPIRY_SECONDS = {session_expiry}
QUMULO_TOKEN_EXPIRY_DAYS   = {token_expiry_days}

STATE_FILE    = "state.json"
USERS_FILE    = "users.json"
SESSIONS_FILE = "sessions.json"
SETTINGS_FILE = "settings.json"

PROXY_PORT  = 8081
'''
    with open(CONFIG_PATH, "w") as f:
        f.write(contents)
    print(f"generate_config.py: wrote {CONFIG_PATH} (admin user: {username})")

if __name__ == "__main__":
    main()
